project_id = "szioctpwyczsdeeypnnv"

[functions."onedrive-auth"]
verify_jwt = false

[functions."onedrive-callback"]
verify_jwt = false

[functions."onedrive-upload"]
verify_jwt = false

[functions."analisar-decisao-ia"]
verify_jwt = true

[functions."arquivar-sharepoint"]
verify_jwt = true

[functions."executar-automacoes"]
verify_jwt = false
